name: Build TvLauncher APK

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-22.04  # 使用更稳定的Ubuntu版本
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Setup Android SDK using custom action
      uses: android-actions/setup-android@v2.1.0  # 使用更新的版本
      
    - name: Build with Gradle
      run: |
        chmod +x ./gradlew
        ./gradlew assembleDebug
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: TvLauncher-App
        path: app/build/outputs/apk/debug/app-debug.apk
